In [ ]:
print("Sanal m s")

In [ ]:

import numpy as np
import tensorflow as tf

def create_matrix(m, n):
  U = tf.Variable(tf.random.normal(shape=(m, n)))
  return U

m = int(input("Enter the number of rows (m): "))
n = int(input("Enter the number of columns (n): "))

matrix = create_matrix(m, n)
print(matrix.numpy())


Enter the number of rows (m): 3
Enter the number of columns (n): 3
[[ 0.91964024  0.428638    0.25708467]
 [ 0.0600898  -0.53361046  1.0128088 ]
 [-0.60201323  0.6058726   1.0772648 ]]


In [ ]:
X = tf.transpose(matrix)
print(X.numpy())


[[ 0.91964024  0.0600898  -0.60201323]
 [ 0.428638   -0.53361046  0.6058726 ]
 [ 0.25708467  1.0128088   1.0772648 ]]


In [ ]:
Y = tf.Variable(tf.random.uniform(shape=(1, m), minval=0, maxval=10, dtype=tf.int32))
print(Y.numpy())


[[4 3 6]]


In [ ]:
p = int(input("Enter the value of p: "))
w1 = tf.Variable(tf.random.uniform(shape=(p, n), minval=0, maxval=1, dtype=tf.float32))
print(w1.numpy())


Enter the value of p: 3
[[0.69037056 0.72264194 0.35657215]
 [0.901765   0.37887454 0.35514164]
 [0.9267317  0.78820574 0.6009046 ]]


In [ ]:
B1 = tf.Variable(tf.random.uniform(shape=(p, 1), minval=0, maxval=1, dtype=tf.float32))
print(B1.numpy())


[[0.48504007]
 [0.19372892]
 [0.32615602]]


In [ ]:
W2 = tf.Variable(tf.zeros(shape=(10, p)))
print(W2.numpy())


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:

B2 = tf.Variable(tf.random.uniform([], minval=-1, maxval=2, dtype=tf.float32))
print(B2.numpy())


0.7912607


In [ ]:
alpha = 0.01

def relu(x):
    return tf.maximum(0, x)

def relu_deriv(x):
    return tf.where(x > 0, tf.ones_like(x), tf.zeros_like(x))

def softmax(x):
    return tf.nn.softmax(x, axis=0)

def one_hot_encode(y, depth):
    return tf.one_hot(y, depth)
Z2 = tf.matmul(W2, A1) + B2
print(Z2.numpy())
for _ in range(15):
    with tf.GradientTape() as tape:
        Z1 = tf.matmul(w1, X) + B1
        A1 = relu(Z1)
        Z2 = tf.matmul(W2, A1) + B2
        A2 = softmax(Z2)

        Y_one_hot = one_hot_encode(Y, 10)

        Y_one_hot = tf.transpose(Y_one_hot, perm=[2, 1, 0])
        Y_one_hot = tf.reshape(Y_one_hot, [10, 3])
        L = 0.5 * tf.reduce_sum(tf.square(A2 - tf.cast(Y_one_hot, tf.float32)))

    # Backward pass
    gradients = tape.gradient(L, [w1, B1, W2, B2])
    dW1, dB1, dW2, dB2 = gradients

    # Parameter updates
    w1.assign_sub(alpha * dW1)
    B1.assign_sub(alpha * dB1)
    W2.assign_sub(alpha * dW2)
    B2.assign_sub(alpha * dB2)

    print(f"Updated W1:\n{w1.numpy()}")
    print(f"Updated B1:\n{B1.numpy()}")
    print(f"Updated W2:\n{W2.numpy()}")
    print(f"Updated B2:\n{B2.numpy()}")


[[0.7263483  0.76961803 0.7595497 ]
 [0.7390389  0.7738443  0.7656496 ]
 [0.73344684 0.7719824  0.7629671 ]
 [0.83424634 0.80555075 0.8112048 ]
 [1.0328014  0.87157065 0.90473515]
 [0.7355496  0.7726891  0.7641171 ]
 [0.89945734 0.827618   0.85004926]
 [0.74122906 0.7745773  0.7667838 ]
 [0.7287095  0.77039576 0.7605041 ]
 [0.74177986 0.77476084 0.7670465 ]]
Updated W1:
[[0.69091904 0.7236117  0.3580473 ]
 [0.90269446 0.3793195  0.3557635 ]
 [0.9274167  0.78919166 0.6024316 ]]
Updated B1:
[[0.48732314]
 [0.19514541]
 [0.32858807]]
Updated W2:
[[-0.01593994 -0.01041126 -0.01706962]
 [-0.01299137 -0.00820238 -0.01387598]
 [-0.01429041 -0.00918852 -0.01527364]
 [ 0.00895259  0.00914509  0.01100508]
 [ 0.0548844   0.04912679  0.06068444]
 [-0.01363706 -0.00912287 -0.01466508]
 [ 0.03326101  0.00415509  0.03220551]
 [-0.01238168 -0.00799592 -0.01328314]
 [-0.01559357 -0.00960884 -0.01659018]
 [-0.01226397 -0.00789719 -0.0131374 ]]
Updated B2:
0.7912607192993164
Updated W1:
[[0.6909585  0.72