In [ ]:
print("sanal m s")

In [3]:
import tensorflow as tf
# np.random.seed(0)
# tf.random.set_seed(0)
m = int(input("enter the no of rows :"))
n = int(input("enter the no of column :"))


enter the no of rows :3
enter the no of column :4


In [5]:

alpha = 0.01

In [10]:
U = tf.random.uniform((m,n))

In [11]:
X = tf.transpose(u)

In [17]:
Y = tf.random.uniform((1, m),maxval=10, dtype=tf.int32)

In [19]:
p = 5

In [27]:
W1 = tf.Variable(tf.random.uniform((p,n)))
print("Matrix W1:\n",W1)

Matrix W1:
 <tf.Variable 'Variable:0' shape=(5, 4) dtype=float32, numpy=
array([[0.16418684, 0.28004825, 0.18143892, 0.50682664],
       [0.46599257, 0.11818612, 0.55899227, 0.6048995 ],
       [0.21985221, 0.92891157, 0.25116467, 0.31829846],
       [0.06491065, 0.88530934, 0.5424533 , 0.38692987],
       [0.48811603, 0.6795474 , 0.816823  , 0.38675404]], dtype=float32)>


In [29]:
B1 = tf.Variable(tf.random.uniform((p,1)))
print("Matrix W1:\n",B1)

Matrix W1:
 <tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[0.5827347 ],
       [0.38821375],
       [0.8265686 ],
       [0.24717581],
       [0.38411677]], dtype=float32)>


In [31]:
W2 = tf.Variable(tf.random.uniform((10,p)))
print("Matrix W1:\n",W2)

Matrix W1:
 <tf.Variable 'Variable:0' shape=(10, 5) dtype=float32, numpy=
array([[0.580551  , 0.6286602 , 0.641574  , 0.8629137 , 0.08965397],
       [0.92937684, 0.25159597, 0.1608653 , 0.9908571 , 0.7720033 ],
       [0.49785244, 0.08044684, 0.17038119, 0.13351643, 0.09870982],
       [0.04765153, 0.87071145, 0.10366881, 0.31473982, 0.5184357 ],
       [0.7411926 , 0.38630235, 0.6625793 , 0.25583208, 0.7011254 ],
       [0.9851682 , 0.6869558 , 0.8399143 , 0.28173363, 0.5065093 ],
       [0.12536645, 0.20266604, 0.56504345, 0.5693778 , 0.49188685],
       [0.885697  , 0.6530309 , 0.75821245, 0.37313795, 0.8016583 ],
       [0.15751576, 0.07459223, 0.6976677 , 0.6534722 , 0.93385625],
       [0.66664004, 0.2594731 , 0.05597901, 0.26091933, 0.75310016]],
      dtype=float32)>


In [33]:
B2 = tf.Variable(tf.random.uniform(([])))
print("Matrix W1:\n",B2)

Matrix W1:
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.17394996>


In [36]:
def softmax(x):
    return tf.nn.softmax(x)

In [39]:
def relu(x):
    return tf.nn.relu(x)

In [41]:
def relu_deriv(x):
    return tf.cast(x = 0,dtype=tf.flow32)